services:
  _defaults:
    autowire: true
    autoconfigure: false # 禁用自动配置以避免冲突

  UserRankingBundle\DataFixtures\:
    resource: '../../DataFixtures/'
    tags: ['doctrine.fixture.orm']
    autoconfigure: true